name: CI Laravel puis SonarCloud

on: [push, pull_request]

jobs:
  tests-and-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # -------------------- Backend Laravel --------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Backend - Install dependencies
        run: cd kempo-solo-api && composer install --prefer-dist --no-progress

      - name: Backend - Setup Laravel
        run: |
          cd kempo-solo-api
          cp .env.example .env
          php artisan key:generate

      - name: Backend - Run tests with coverage
        run: |
          cd kempo-solo-api
          mkdir -p storage/coverage
          php artisan test --coverage-clover storage/coverage/coverage.xml


      # -------------------- Analyse SonarCloud --------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

